name: Test

on: [push]

jobs:
  test:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install Go
        uses: actions/setup-go@v2-beta
        with:
          go-version: '^1.14.2'
      - name: Setup go modules cache
        uses: actions/cache@v1
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
      - name: Install Capstone
        run: sudo apt-get install capstone
      - name: Run unit tests
        run: go test ./...
