name: Test

on: [push]

jobs:
  test:
    name: Unit tests
    runs-on: ubuntu-latest
    container: golang:1.14.2-alpine
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup go modules cache
        uses: actions/cache@v1
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
      - name: Install C Toolchain and Dependencies
        run: apk add git build-base capstone-dev
      - name: Run unit tests
        run: go test ./...
